### ISSUE TITLE
SAE平台下，初始化需要哪些操作呢？

### ISSUE THREAD

**Issue by xuelu520** [Urinx/weChat_php#1]
SAE平台下，初始化需要哪些操作呢？

**Comment by Urinx** [comment]
如果你要把微信后台放到SAE上，先按照微信公众号的要求配置好URL和Token，然后把文件上传上去就可以了（我这里就是两个文件：index.php和wechat-api.php）。当然有用到数据库什么的要按照SAE的文档另行配置。
